name: CI/CD Pipeline
on:
  push:
    branches:
      - main
env:
  ACTIONS_RUNNER_DEBUG: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Compilar Código
        run: mvn clean package

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Ejecutar Pruebas
        run: mvn test