name: CI/CD Pipeline
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Código
        uses: actions/checkout@v2

      - name: Compilar Código
        run: mvn clean package

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Ejecutar Pruebas
        run: mvn test